package com.llburgers.service;

import com.llburgers.domain.Admin;
import com.llburgers.domain.User;
import com.llburgers.domain.enums.AdminLevel;
import com.llburgers.domain.enums.Role;
import com.llburgers.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Integration tests for {@link IUserService}.
 * Hits the real Supabase PostgreSQL database.
 * Data written by these tests is intentionally kept in the database.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("test")
class UserServiceImplTest {

    @Autowired
    private IUserService userService;

    @Autowired
    private UserRepository userRepository;

    private User savedUser;

    @BeforeEach
    void setUp() {
        Admin admin = Admin.builder()
                .name("Test Admin")
                .email("test.admin." + UUID.randomUUID() + "@llburgers.com")
                .password("securePass99")
                .phone(null)
                .role(Role.ADMIN)
                .adminLevel(AdminLevel.SUPER_ADMIN)
                .active(true)
                .build();
        savedUser = userRepository.save(admin);
    }

    // ─── PASSING TESTS ────────────────────────────────────────────────────────

    @Test
    @DisplayName("PASS – create() persists a new user and returns it with a generated ID")
    void create_persistsUserAndReturnsWithId() {
        Admin newAdmin = Admin.builder()
                .name("Created Admin")
                .email("created.admin." + UUID.randomUUID() + "@llburgers.com")
                .password("createdPass1")
                .phone(null)
                .role(Role.ADMIN)
                .adminLevel(AdminLevel.ADMIN)
                .active(true)
                .build();

        User created = userService.create(newAdmin);

        assertNotNull(created.getId(), "ID should be generated by the database");
        assertTrue(userRepository.existsById(created.getId()), "User should exist in the database");
        assertEquals("Created Admin", created.getName());
        assertTrue(created.isActive());
    }

    @Test
    @DisplayName("PASS – read() fetches the correct user from the database by ID")
    void read_whenUserExists_returnsUserFromDb() {
        User fetched = userService.read(savedUser.getId());

        assertNotNull(fetched);
        assertEquals(savedUser.getId(), fetched.getId());
        assertEquals(savedUser.getEmail(), fetched.getEmail());
        assertEquals(Role.ADMIN, fetched.getRole());
    }

    // ─── FAILING TESTS ────────────────────────────────────────────────────────

    @Test
    @DisplayName("FAIL – read() asserts the wrong email (intentionally wrong assertion)")
    void read_assertsWrongEmail_fail() {
        User fetched = userService.read(savedUser.getId());

        // ❌ The real email contains a UUID — this hardcoded value will never match
        assertEquals("wrong-email@llburgers.com", fetched.getEmail(),
                "Intentionally wrong assertion — this test should FAIL");
    }

    @Test
    @DisplayName("FAIL – read() with a random ID that does not exist in the database expects no exception (intentionally wrong)")
    void read_nonExistentId_expectsNoException_fail() {
        UUID ghostId = UUID.randomUUID();

        // ❌ UserServiceImpl throws IllegalArgumentException for unknown IDs.
        // assertDoesNotThrow will fail because the exception IS thrown.
        assertDoesNotThrow(
                () -> userService.read(ghostId),
                "Intentionally wrong — UserServiceImpl throws for unknown IDs, this test should FAIL"
        );
    }
}
